'use strict';

/**
 * Generate harness-specific files from the single source of truth
 * (agents/, commands/, rules/trading/, skills/), the way ECC keeps one canonical
 * tree and derives per-harness adapters. Generated files are committed and a
 * test fails when they drift (`node scripts/sync-harness.js --check`).
 *
 *   workspace/AGENTS.md, CLAUDE.md, QWEN.md   operator instructions for any harness
 *   .codex/agents/<role>.toml                 Codex agent roles
 *   qwen/agents/<role>.md                     Qwen subagents (Qwen tool ids)
 *   qwen/commands/<name>.md                   Qwen commands ({{args}})
 */

const fs = require('fs');
const path = require('path');
const { parseFrontmatter } = require('./frontmatter');

const GENERATED = '<!-- Generated by scripts/sync-harness.js. Edit the sources, not this file. -->';
const TOML_GENERATED = '# Generated by scripts/sync-harness.js from agents/<role>.md. Edit the source, not this file.';

const QWEN_TOOLS = {
  Read: 'read_file', Write: 'write_file', Edit: 'edit', Bash: 'run_shell_command', Grep: 'grep_search',
  Glob: 'glob', WebSearch: 'web_search', WebFetch: 'web_fetch', Skill: 'skill', Agent: 'task',
};
// Agents that only analyse may write scratch files; nobody needs network sandbox access.
const CODEX_SANDBOX = { default: 'read-only', writes: 'workspace-write' };

function readSorted(dir, suffix) {
  return fs.readdirSync(dir).filter(f => f.endsWith(suffix)).sort();
}

function loadAgents(root) {
  return readSorted(path.join(root, 'agents'), '.md').map(f => {
    const { data, body } = parseFrontmatter(fs.readFileSync(path.join(root, 'agents', f), 'utf8'));
    return { file: f, ...data, tools: String(data.tools || '').split(',').map(t => t.trim()).filter(Boolean), body: body.trim() };
  });
}

function tomlString(text) {
  // Multi-line literal strings can't contain ''' ; fall back to an escaped basic string.
  if (!text.includes("'''")) return `'''\n${text}\n'''`;
  return JSON.stringify(text);
}

function codexAgentToml(agent) {
  const writes = agent.tools.some(t => ['Write', 'Edit', 'Bash'].includes(t));
  const mcp = agent.tools.filter(t => t.startsWith('mcp__projectx__')).map(t => t.replace('mcp__projectx__', ''));
  const instructions = [
    `You are the ${agent.name} role of the futures trading harness. ${agent.description}`,
    mcp.length ? `projectx MCP tools you may use: ${mcp.join(', ')}. Do not call any other projectx tool.` : 'Do not call any projectx MCP tool.',
    '',
    agent.body,
  ].join('\n');
  return [
    TOML_GENERATED,
    `sandbox_mode = "${writes ? CODEX_SANDBOX.writes : CODEX_SANDBOX.default}"`,
    '',
    `developer_instructions = ${tomlString(instructions)}`,
    '',
  ].join('\n');
}

function codexRoleName(name) {
  return name.replace(/-/g, '_');
}

function codexAgentsTable(agents, configDir) {
  return agents.flatMap(a => [
    `[agents.${codexRoleName(a.name)}]`,
    `description = ${JSON.stringify(a.description)}`,
    `config_file = ${JSON.stringify(path.posix.join(configDir, `${a.name}.toml`))}`,
    '',
  ]).join('\n');
}

function qwenAgentMd(agent) {
  const tools = agent.tools.map(t => QWEN_TOOLS[t] || t);
  return [
    '---',
    `name: ${agent.name}`,
    `description: ${JSON.stringify(agent.description)}`,
    'tools:',
    ...tools.map(t => `  - ${t}`),
    '---',
    '',
    GENERATED,
    '',
    agent.body,
    '',
  ].join('\n');
}

function qwenCommandMd(text) {
  const { data, body } = parseFrontmatter(text);
  return [
    '---',
    `description: ${JSON.stringify(data.description)}`,
    '---',
    '',
    body.trim().replace(/\$ARGUMENTS/g, '{{args}}'),
    '',
  ].join('\n');
}

function workspaceAgentsMd(root) {
  const rules = readSorted(path.join(root, 'rules', 'trading'), '.md')
    .map(f => fs.readFileSync(path.join(root, 'rules', 'trading', f), 'utf8').trim().replace(/^# /m, '## '));
  const skills = fs.readdirSync(path.join(root, 'skills'))
    .filter(d => fs.existsSync(path.join(root, 'skills', d, 'SKILL.md')))
    .sort()
    .map(d => {
      const { data } = parseFrontmatter(fs.readFileSync(path.join(root, 'skills', d, 'SKILL.md'), 'utf8'));
      return `- \`${d}\` (skills/${d}/SKILL.md): ${data.description}`;
    });
  const agents = loadAgents(root).map(a => `- \`${a.name}\` (agents/${a.name}.md): ${a.description}`);
  return [
    GENERATED,
    '',
    '# Futures Trading Harness: Operator Instructions',
    '',
    'You are the head trader of an automated futures desk trading TopstepX',
    'through the `projectx` MCP server. These instructions apply to every',
    'harness (Claude Code, Codex, Qwen Code, or any agent that reads AGENTS.md).',
    '',
    '## Start here',
    '',
    '- The harness root (`FTH_ROOT`) is the parent of this `workspace/` folder;',
    '  scripts live in `$FTH_ROOT/scripts/`, strategies in `$FTH_ROOT/strategies/`.',
    '- Before trading, read the skill you need from `$FTH_ROOT/skills/<name>/SKILL.md`',
    '  if your harness has not loaded it. Start with `trade-session`, `premarket`,',
    '  `end-of-day`, or `autonomous-trading`.',
    '- Strategies are Markdown files: `node "$FTH_ROOT/scripts/strategies.js" list`.',
    '- Delegate to the agent roles below with your harness\'s subagents; without',
    '  subagents, read the role file and play the role yourself.',
    '',
    '## Rules (always apply)',
    '',
    ...rules.flatMap(r => [r, '']),
    '## Skills',
    '',
    ...skills,
    '',
    '## Agent roles',
    '',
    ...agents,
    '',
  ].join('\n');
}

/** Map of relative path -> expected file content. */
function expectedFiles(root) {
  const files = {};
  const agentsMd = workspaceAgentsMd(root);
  files['workspace/AGENTS.md'] = agentsMd;
  files['workspace/CLAUDE.md'] = `${GENERATED}\n\n@AGENTS.md\n`;
  files['workspace/QWEN.md'] = agentsMd;
  for (const a of loadAgents(root)) {
    files[`.codex/agents/${a.name}.toml`] = codexAgentToml(a);
    files[`qwen/agents/${a.name}.md`] = qwenAgentMd(a);
  }
  for (const f of readSorted(path.join(root, 'commands'), '.md')) {
    files[`qwen/commands/${f}`] = qwenCommandMd(fs.readFileSync(path.join(root, 'commands', f), 'utf8'));
  }
  return files;
}

/** Generated directories whose stale files should be removed. */
const OWNED_DIRS = ['.codex/agents', 'qwen/agents', 'qwen/commands'];

function syncHarness(root, { check = false } = {}) {
  const expected = expectedFiles(root);
  const stale = [];
  for (const [rel, content] of Object.entries(expected)) {
    const file = path.join(root, rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === content) continue;
    stale.push(rel);
    if (!check) {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    }
  }
  for (const dir of OWNED_DIRS) {
    const abs = path.join(root, dir);
    if (!fs.existsSync(abs)) continue;
    for (const f of fs.readdirSync(abs)) {
      const rel = `${dir}/${f}`;
      if (expected[rel] !== undefined) continue;
      stale.push(`${rel} (orphan)`);
      if (!check) fs.unlinkSync(path.join(abs, f));
    }
  }
  return stale;
}

module.exports = {
  QWEN_TOOLS,
  loadAgents,
  codexAgentToml,
  codexRoleName,
  codexAgentsTable,
  qwenAgentMd,
  qwenCommandMd,
  workspaceAgentsMd,
  expectedFiles,
  syncHarness,
};
